export const DESCRIPTION =
  "Run any Azure CLI command through one compact passthrough: TOON output, redacted secrets, gated mutations";

export const TOP_LEVEL_HELP = [
  "az-axi                                   # live context: subscription, tenant, resource groups",
  "az-axi <module> <verb> [args]            # any az command, compacted (az-axi vm list -g rg)",
  "az-axi az <module> <verb> [args]         # same, for modules that clash with an az-axi command",
  "az-axi find [<group>] [<text>]           # search az command groups and commands",
  "az-axi <group> --help                    # compacted az help for a group",
  "az-axi doctor                            # az install, login, subscription, extensions",
  "az-axi setup [install|status|uninstall]  # ambient session hooks for agents",
  "az-axi update [--check]                  # self-update",
  "",
  "Examples:",
  "  az-axi group list",
  "  az-axi vm list -g platform --fields name,location,powerState",
  "  az-axi webapp show -g web -n contoso-api",
  "  az-axi monitor log-analytics query -w <workspace-id> --analytics-query \"Heartbeat | take 5\"",
  "  az-axi rest --method get --url https://management.azure.com/subscriptions?api-version=2022-12-01",
  "  az-axi vm start -g platform -n build-01 --execute",
  "  az-axi group delete -n scratch --yes --execute --confirm",
  "",
  "Safety: reads run immediately; mutations return the exact command as a dry-run plan until",
  "--execute is passed, and delete-style commands additionally need --confirm. Secrets are",
  "redacted unless --reveal. az-axi never prompts — run `az login` yourself.",
  "",
  "az-axi flags: --fields a,b  --limit <n>  --for <duration>  --full  --reveal  --execute  --confirm  --dry-run  --raw",
  "Every other flag (--subscription, -g, --query, --name, ...) is forwarded to az unchanged.",
].join("\n");

const PASSTHROUGH_HELP = [
  "az-axi <module> <verb> [args] [az flags] [az-axi flags]",
  "",
  "Every Azure CLI module works without an az-axi-specific wrapper. Output is TOON:",
  "lists are capped at 50 rows with a total count, records are pruned, long strings are",
  "truncated. High-traffic commands (group/vm/webapp/storage/aks/containerapp/keyvault/",
  "network/sql/ad/role/...) use a curated column set; everything else falls back to",
  "generic compaction.",
  "",
  "az-axi flags:",
  "  --fields a,b.c   pick columns (dot paths allowed, e.g. sku.name)",
  "  --limit <n>      rows to show (default 50; lines for a log stream, default 200)",
  "  --for <duration> how long to capture a log stream (default 15s, e.g. --for 60s)",
  "  --full           no truncation, no pruning, no row cap",
  "  --reveal         do not redact secret-looking values",
  "  --execute        actually run a mutating command",
  "  --confirm        additionally required for delete-style commands",
  "  --dry-run        print the exact az command without running it",
  "  --raw            return az stdout as text instead of compacted TOON",
  "",
  "Examples:",
  "  az-axi aks list --fields name,resourceGroup,kubernetesVersion",
  "  az-axi storage account list -g data --limit 10",
  "  az-axi webapp log tail -g web -n contoso-api --for 30s",
  "  az-axi keyvault secret show --vault-name kv -n api-key --reveal",
  "  az-axi containerapp update -g rg -n api --image ghcr.io/acme/api:1.2.3 --execute",
].join("\n");

export const COMMAND_HELP: Record<string, string> = {
  run: PASSTHROUGH_HELP,
  find: [
    "az-axi find [<group>...] [<text>...] [--limit 30] [--full]",
    "",
    "Searches the Azure CLI's own help tree — no bundled catalog, so it never goes stale.",
    "The longest leading token sequence that is a real command group is expanded; the rest",
    "filters that group's subgroups and commands by name and summary.",
    "",
    "Examples:",
    "  az-axi find                     # every top-level az group",
    "  az-axi find storage             # groups and commands matching 'storage'",
    "  az-axi find network vnet peer   # search inside `az network vnet`",
  ].join("\n"),
  doctor: [
    "az-axi doctor [--full]",
    "",
    "Reports the Azure CLI version, installed extensions, sign-in state, active subscription,",
    "tenant, and cloud. Exit code 0 even when a check fails — read `status`.",
  ].join("\n"),
  setup: [
    "az-axi setup [install|status|uninstall] [--scope user|project]",
    "",
    "Installs a SessionStart hook for Claude Code, Codex, and OpenCode so every session starts",
    "with the active Azure context. `--scope project` writes the repository-local config instead.",
  ].join("\n"),
};
